language: python

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py develop

script:
  - flake8 .
  - coverage run -m unittest discover
  - coverage report

after_success:
  - coveralls