language: python

virtualenv:
  system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apy-get install python-scipy

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py develop

script:
  - flake8 .
  - coverage run -m unittest discover
  - coverage report

after_success:
  - coveralls